/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ThreatLibraryRouteImport } from './routes/threat-library'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SimulatorRouteImport } from './routes/simulator'
import { Route as ScamRadarRouteImport } from './routes/scam-radar'
import { Route as SafetyTipsRouteImport } from './routes/safety-tips'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'

const ThreatLibraryRoute = ThreatLibraryRouteImport.update({
  id: '/threat-library',
  path: '/threat-library',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SimulatorRoute = SimulatorRouteImport.update({
  id: '/simulator',
  path: '/simulator',
  getParentRoute: () => rootRouteImport,
} as any)
const ScamRadarRoute = ScamRadarRouteImport.update({
  id: '/scam-radar',
  path: '/scam-radar',
  getParentRoute: () => rootRouteImport,
} as any)
const SafetyTipsRoute = SafetyTipsRouteImport.update({
  id: '/safety-tips',
  path: '/safety-tips',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/safety-tips': typeof SafetyTipsRoute
  '/scam-radar': typeof ScamRadarRoute
  '/simulator': typeof SimulatorRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/threat-library': typeof ThreatLibraryRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/safety-tips': typeof SafetyTipsRoute
  '/scam-radar': typeof ScamRadarRoute
  '/simulator': typeof SimulatorRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/threat-library': typeof ThreatLibraryRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/safety-tips': typeof SafetyTipsRoute
  '/scam-radar': typeof ScamRadarRoute
  '/simulator': typeof SimulatorRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/threat-library': typeof ThreatLibraryRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/dashboard'
    | '/safety-tips'
    | '/scam-radar'
    | '/simulator'
    | '/sitemap.xml'
    | '/threat-library'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/dashboard'
    | '/safety-tips'
    | '/scam-radar'
    | '/simulator'
    | '/sitemap.xml'
    | '/threat-library'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/dashboard'
    | '/safety-tips'
    | '/scam-radar'
    | '/simulator'
    | '/sitemap.xml'
    | '/threat-library'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  DashboardRoute: typeof DashboardRoute
  SafetyTipsRoute: typeof SafetyTipsRoute
  ScamRadarRoute: typeof ScamRadarRoute
  SimulatorRoute: typeof SimulatorRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ThreatLibraryRoute: typeof ThreatLibraryRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/threat-library': {
      id: '/threat-library'
      path: '/threat-library'
      fullPath: '/threat-library'
      preLoaderRoute: typeof ThreatLibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/simulator': {
      id: '/simulator'
      path: '/simulator'
      fullPath: '/simulator'
      preLoaderRoute: typeof SimulatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scam-radar': {
      id: '/scam-radar'
      path: '/scam-radar'
      fullPath: '/scam-radar'
      preLoaderRoute: typeof ScamRadarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/safety-tips': {
      id: '/safety-tips'
      path: '/safety-tips'
      fullPath: '/safety-tips'
      preLoaderRoute: typeof SafetyTipsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  DashboardRoute: DashboardRoute,
  SafetyTipsRoute: SafetyTipsRoute,
  ScamRadarRoute: ScamRadarRoute,
  SimulatorRoute: SimulatorRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ThreatLibraryRoute: ThreatLibraryRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
